// wayforkctl drives wayfork-service without the app (the macOS `wayforkctl` / `--dev-apply`
// counterpart, docs/ROADMAP-windows.md WM2): it talks to the pipe and assembles plan
// files from generated sing-box configs and OpenVPN profiles.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"wayfork/service/internal/core"
	"wayfork/service/internal/ipc"
)

const usage = `usage:
  wayforkctl info | status | stop | diagnostics
  wayforkctl apply <plan.json>
  wayforkctl reconnect <tunnel id>
  wayforkctl watch                      subscribe and print pushes until Ctrl-C
  wayforkctl plan [flags] -o <plan.json>
      --config <sing-box.json>          generated by the app / the Dart core
      --rules <dir>                     directory with rules-*.json
      --ovpn <id>=<adapter>:<file.ovpn>[:<user>:<password>][:passphrase=<p>]
      --no-dns-override                 overrideSystemDNS=false
      --log-level <level>               error | warning | info | debug`

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, usage)
		os.Exit(2)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	var err error
	switch os.Args[1] {
	case "info":
		err = call(ctx, func(c *ipc.Client) (any, error) { return c.GetInfo(ctx) })
	case "status":
		err = call(ctx, func(c *ipc.Client) (any, error) { return c.GetStatus(ctx) })
	case "stop":
		err = call(ctx, func(c *ipc.Client) (any, error) { return c.Stop(ctx) })
	case "diagnostics":
		err = call(ctx, func(c *ipc.Client) (any, error) { return c.CollectDiagnostics(ctx) })
	case "apply":
		if len(os.Args) != 3 {
			err = errors.New("apply needs a plan file")
			break
		}
		var plan core.RuntimePlan
		if err = readJSON(os.Args[2], &plan); err != nil {
			break
		}
		err = call(ctx, func(c *ipc.Client) (any, error) { return c.Apply(ctx, plan) })
	case "reconnect":
		if len(os.Args) != 3 {
			err = errors.New("reconnect needs a tunnel id")
			break
		}
		err = call(ctx, func(c *ipc.Client) (any, error) { return c.Reconnect(ctx, os.Args[2]) })
	case "watch":
		err = watch()
	case "plan":
		err = buildPlan(os.Args[2:])
	default:
		fmt.Fprintln(os.Stderr, usage)
		os.Exit(2)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "wayforkctl:", err)
		os.Exit(1)
	}
}

func connect(ctx context.Context, events ipc.EventFunc) (*ipc.Client, error) {
	pipe, err := ipc.DialPipe(ipc.PipeName)
	if err != nil {
		return nil, err
	}
	client := ipc.NewClient(pipe, events)
	hello, err := client.Hello(ctx)
	if err != nil {
		client.Close()
		return nil, err
	}
	if hello.Protocol != ipc.ProtocolVersion || hello.PlanVersion != core.PlanVersion {
		client.Close()
		return nil, fmt.Errorf("service speaks protocol %d / plan %d, this tool %d / %d",
			hello.Protocol, hello.PlanVersion, ipc.ProtocolVersion, core.PlanVersion)
	}
	return client, nil
}

func call(ctx context.Context, request func(*ipc.Client) (any, error)) error {
	client, err := connect(ctx, nil)
	if err != nil {
		return err
	}
	defer client.Close()
	result, err := request(client)
	if err != nil {
		return err
	}
	return printJSON(result)
}

func printJSON(value any) error {
	data, err := core.MarshalWire(value)
	if err != nil {
		return err
	}
	var pretty bytes.Buffer
	if err := json.Indent(&pretty, data, "", "  "); err != nil {
		return err
	}
	fmt.Println(pretty.String())
	return nil
}

func watch() error {
	ctx := context.Background()
	client, err := connect(ctx, func(event string, data json.RawMessage) {
		var pretty bytes.Buffer
		if json.Compact(&pretty, data) != nil {
			pretty.Write(data)
		}
		fmt.Printf("%s %s %s\n", time.Now().Format("15:04:05"), event, pretty.String())
	})
	if err != nil {
		return err
	}
	defer client.Close()
	if _, err := client.Subscribe(ctx); err != nil {
		return err
	}
	select {}
}

func readJSON(path string, target any) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, target)
}

// ovpnFlags collects repeated --ovpn values.
type ovpnFlags []string

func (f *ovpnFlags) String() string     { return strings.Join(*f, ",") }
func (f *ovpnFlags) Set(v string) error { *f = append(*f, v); return nil }

func buildPlan(args []string) error {
	flags := flag.NewFlagSet("plan", flag.ContinueOnError)
	config := flags.String("config", "", "sing-box.json")
	rules := flags.String("rules", "", "directory with rules-*.json")
	output := flags.String("o", "", "output plan file")
	noDNS := flags.Bool("no-dns-override", false, "overrideSystemDNS=false")
	level := flags.String("log-level", "info", "log level")
	var tunnels ovpnFlags
	flags.Var(&tunnels, "ovpn", "<id>=<adapter>:<file>[:<user>:<password>][:passphrase=<p>]")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if *config == "" || *output == "" {
		return errors.New("plan needs --config and -o")
	}
	configText, err := os.ReadFile(*config)
	if err != nil {
		return err
	}
	logLevel, err := core.ParseLogLevel(*level)
	if err != nil {
		return err
	}
	ruleSets := map[string]string{}
	if *rules != "" {
		entries, err := os.ReadDir(*rules)
		if err != nil {
			return err
		}
		for _, entry := range entries {
			name := entry.Name()
			if name != core.DirectRuleSet && name != core.DirectIPRuleSet && !core.IsRuleSet(name) {
				continue
			}
			text, err := os.ReadFile(filepath.Join(*rules, name))
			if err != nil {
				return err
			}
			ruleSets[name] = string(text)
		}
	}
	runtimes := []core.OpenVPNRuntime{}
	for _, spec := range tunnels {
		runtime, err := parseTunnel(spec)
		if err != nil {
			return err
		}
		runtimes = append(runtimes, runtime)
	}
	sort.Slice(runtimes, func(i, j int) bool { return runtimes[i].ID < runtimes[j].ID })
	plan := core.RuntimePlan{
		Version: core.PlanVersion,
		SingBox: core.SingBoxPlan{Config: string(configText), ConfigHash: core.SHA256Hex(string(configText)), RuleSets: ruleSets},
		OpenVPN: runtimes, AutoReconnect: true, LogLevel: logLevel, OverrideSystemDNS: !*noDNS,
	}
	if err := core.ValidatePlan(plan); err != nil {
		return err
	}
	data, err := core.MarshalWire(plan)
	if err != nil {
		return err
	}
	if err := os.WriteFile(*output, append(data, '\n'), 0o600); err != nil {
		return err
	}
	fmt.Printf("wrote %s (planHash %s, %d tunnel(s), %d rule-set file(s))\n", *output, plan.PlanHash()[:12], len(runtimes), len(ruleSets))
	return nil
}

// parseTunnel reads `<id>=<adapter>:<file>[:<user>:<password>][:passphrase=<p>]`.
func parseTunnel(spec string) (core.OpenVPNRuntime, error) {
	id, rest, ok := strings.Cut(spec, "=")
	if !ok {
		return core.OpenVPNRuntime{}, fmt.Errorf("--ovpn %q: expected <id>=<adapter>:<file>", spec)
	}
	parts := strings.Split(rest, ":")
	if len(parts) < 2 {
		return core.OpenVPNRuntime{}, fmt.Errorf("--ovpn %q: expected <adapter>:<file>", spec)
	}
	adapter, file := parts[0], parts[1]
	// A drive letter in the file path is one more colon.
	if len(parts) > 2 && len(file) == 1 && file[0] >= 'A' && file[0] <= 'z' {
		file = file + ":" + parts[2]
		parts = append(parts[:2], parts[3:]...)
	}
	config, err := os.ReadFile(file)
	if err != nil {
		return core.OpenVPNRuntime{}, err
	}
	runtime := core.OpenVPNRuntime{ID: strings.ToLower(id), Interface: adapter, Config: string(config)}
	extras := parts[2:]
	var passphrase *string
	if len(extras) > 0 && strings.HasPrefix(extras[len(extras)-1], "passphrase=") {
		value := strings.TrimPrefix(extras[len(extras)-1], "passphrase=")
		passphrase = &value
		extras = extras[:len(extras)-1]
	}
	if len(extras) == 2 {
		runtime.Credentials = &core.Credentials{Username: extras[0], Password: extras[1]}
	} else if len(extras) != 0 {
		return core.OpenVPNRuntime{}, fmt.Errorf("--ovpn %q: expected [:<user>:<password>][:passphrase=<p>]", spec)
	}
	runtime.KeyPassphrase = passphrase
	runtime.ConfigHash = core.ComputeOpenVPNConfigHash(runtime.Config, runtime.Credentials, runtime.KeyPassphrase)
	return runtime, nil
}
