import Darwin
import Foundation

/// Loopback controller sing-box exposes for traffic sampling (F9). Generated by the daemon
/// for every config it writes; the secret never leaves the daemon
/// (docs/design/05-daemon.md, "Traffic sampling").
public struct ClashAPIEndpoint: Sendable, Hashable {
    public var port: UInt16
    public var secret: String

    public init(port: UInt16, secret: String) {
        self.port = port
        self.secret = secret
    }

    /// `experimental.clash_api.external_controller`.
    public var externalController: String { "127.0.0.1:\(port)" }

    public var connectionsURL: URL {
        URL(string: "http://\(externalController)/connections")!
    }

    /// A free loopback port and a fresh 32-byte secret.
    public static func generate() throws(ClashAPIError) -> ClashAPIEndpoint {
        ClashAPIEndpoint(port: try freeLoopbackPort(), secret: randomSecret())
    }

    /// Binds `127.0.0.1:0`, reads the port the kernel picked and releases it again. sing-box
    /// may still lose the race for it; that surfaces as a normal start failure.
    public static func freeLoopbackPort() throws(ClashAPIError) -> UInt16 {
        let fd = socket(AF_INET, SOCK_STREAM, 0)
        guard fd >= 0 else { throw .portProbeFailed(errno) }
        defer { close(fd) }
        var address = sockaddr_in()
        address.sin_len = UInt8(MemoryLayout<sockaddr_in>.size)
        address.sin_family = sa_family_t(AF_INET)
        address.sin_port = 0
        address.sin_addr.s_addr = UInt32(INADDR_LOOPBACK).bigEndian
        let length = socklen_t(MemoryLayout<sockaddr_in>.size)
        let bound = withUnsafePointer(to: &address) { pointer in
            pointer.withMemoryRebound(to: sockaddr.self, capacity: 1) { bind(fd, $0, length) }
        }
        guard bound == 0 else { throw .portProbeFailed(errno) }
        var assigned = sockaddr_in()
        var assignedLength = length
        let read = withUnsafeMutablePointer(to: &assigned) { pointer in
            pointer.withMemoryRebound(to: sockaddr.self, capacity: 1) {
                getsockname(fd, $0, &assignedLength)
            }
        }
        guard read == 0 else { throw .portProbeFailed(errno) }
        let port = UInt16(bigEndian: assigned.sin_port)
        guard port != 0 else { throw .portProbeFailed(0) }
        return port
    }

    /// 32 random bytes, hex-encoded (`SystemRandomNumberGenerator` is cryptographically
    /// secure on Apple platforms).
    public static func randomSecret() -> String {
        var generator = SystemRandomNumberGenerator()
        return (0..<32).map { _ in
            String(format: "%02x", UInt8.random(in: .min ... .max, using: &generator))
        }
        .joined()
    }
}

public enum ClashAPIError: Error, Hashable, Sendable {
    case portProbeFailed(Int32)
    /// The config is not a JSON object.
    case notAnObject
    case serialization(String)
}

/// Adds `experimental.clash_api` to the config the app generated. The generator and its
/// golden files never contain it; the app's `configHash` stays that of the original text.
public enum ClashAPIConfig {
    public static func inject(_ endpoint: ClashAPIEndpoint, into config: String)
        throws(ClashAPIError)
        -> String
    {
        let parsed: Any
        do {
            parsed = try JSONSerialization.jsonObject(with: Data(config.utf8))
        } catch {
            throw .serialization("\(error)")
        }
        guard var root = parsed as? [String: Any] else { throw .notAnObject }
        var experimental = root["experimental"] as? [String: Any] ?? [:]
        experimental["clash_api"] = [
            "external_controller": endpoint.externalController,
            "secret": endpoint.secret,
        ]
        root["experimental"] = experimental
        let data: Data
        do {
            data = try JSONSerialization.data(
                withJSONObject: root,
                options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes])
        } catch {
            throw .serialization("\(error)")
        }
        return String(decoding: data, as: UTF8.self) + "\n"
    }
}
