package core

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"net"
)

// ClashAPIEndpoint is the loopback controller sing-box exposes for traffic sampling (F9).
// Generated by the service for every config it writes; the secret never leaves it
// (docs/design/05-daemon.md, "Traffic sampling").
type ClashAPIEndpoint struct {
	Port   uint16
	Secret string
}

// ExternalController is `experimental.clash_api.external_controller`.
func (e ClashAPIEndpoint) ExternalController() string {
	return fmt.Sprintf("127.0.0.1:%d", e.Port)
}

// ConnectionsURL is the `GET /connections` endpoint.
func (e ClashAPIEndpoint) ConnectionsURL() string {
	return "http://" + e.ExternalController() + "/connections"
}

// GenerateClashAPIEndpoint picks a free loopback port and a fresh 32-byte secret.
func GenerateClashAPIEndpoint() (ClashAPIEndpoint, error) {
	port, err := FreeLoopbackPort()
	if err != nil {
		return ClashAPIEndpoint{}, err
	}
	secret, err := RandomSecret()
	if err != nil {
		return ClashAPIEndpoint{}, err
	}
	return ClashAPIEndpoint{Port: port, Secret: secret}, nil
}

// FreeLoopbackPort binds `127.0.0.1:0`, reads the port the kernel picked and releases it
// again. sing-box may still lose the race for it; that surfaces as a normal start failure.
func FreeLoopbackPort() (uint16, error) {
	listener, err := net.Listen("tcp4", "127.0.0.1:0")
	if err != nil {
		return 0, fmt.Errorf("probing a loopback port: %w", err)
	}
	defer listener.Close()
	address, ok := listener.Addr().(*net.TCPAddr)
	if !ok || address.Port == 0 {
		return 0, errors.New("probing a loopback port: no port assigned")
	}
	return uint16(address.Port), nil
}

// RandomSecret is 32 random bytes, hex-encoded.
func RandomSecret() (string, error) {
	var raw [32]byte
	if _, err := rand.Read(raw[:]); err != nil {
		return "", fmt.Errorf("generating the Clash API secret: %w", err)
	}
	return hex.EncodeToString(raw[:]), nil
}

// InjectClashAPI adds `experimental.clash_api` to the config the app generated. The
// generator and its golden files never contain it; the app's configHash stays that of the
// original text. Numbers survive untouched; keys come out sorted, two-space indented.
func InjectClashAPI(endpoint ClashAPIEndpoint, config string) (string, error) {
	decoder := json.NewDecoder(bytes.NewReader([]byte(config)))
	decoder.UseNumber()
	var root map[string]any
	if err := decoder.Decode(&root); err != nil {
		return "", fmt.Errorf("sing-box config is not a JSON object: %w", err)
	}
	if root == nil {
		return "", errors.New("sing-box config is not a JSON object")
	}
	experimental, _ := root["experimental"].(map[string]any)
	if experimental == nil {
		if root["experimental"] != nil {
			return "", errors.New("sing-box config: experimental is not an object")
		}
		experimental = map[string]any{}
	}
	experimental["clash_api"] = map[string]any{
		"external_controller": endpoint.ExternalController(),
		"secret":              endpoint.Secret,
	}
	root["experimental"] = experimental
	var out bytes.Buffer
	encoder := json.NewEncoder(&out)
	encoder.SetEscapeHTML(false)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(root); err != nil {
		return "", fmt.Errorf("re-encoding the sing-box config: %w", err)
	}
	return out.String(), nil
}

// ClashConnection is one entry of `GET /connections`, reduced to what the sampler and the
// connection cut need. Upload and Download are cumulative for the connection's lifetime;
// the metadata fields stay inside the service.
type ClashConnection struct {
	ID string
	// Outbound chain, e.g. `["t-<tunnel id>"]` or `["direct"]`.
	Chains   []string
	Upload   uint64
	Download uint64
	// `metadata.network`: "tcp" or "udp" (the dead-UDP detector keys on the latter).
	Network string
	// `metadata.host`: the fake-ip or sniffed domain; empty for a bare IP connection.
	Host string
	// `metadata.destinationIP`.
	DestinationIP string
	// `metadata.processPath`; empty when sing-box could not find the process.
	ProcessPath string
}

// ClashConnections is the decoded `GET /connections` reply.
type ClashConnections struct {
	Connections []ClashConnection
}

type clashConnectionWire struct {
	ID       string   `json:"id"`
	Chains   []string `json:"chains"`
	Upload   int64    `json:"upload"`
	Download int64    `json:"download"`
	Metadata *struct {
		Network       string `json:"network"`
		Host          string `json:"host"`
		DestinationIP string `json:"destinationIP"`
		ProcessPath   string `json:"processPath"`
	} `json:"metadata"`
}

// DecodeClashConnections decodes sing-box's Clash API reply, tolerating a `null`
// connection list, missing metadata and missing or negative counters. Other fields
// (`downloadTotal`, `memory`, the rest of `metadata`) are ignored.
func DecodeClashConnections(data []byte) (ClashConnections, error) {
	var wire struct {
		Connections []clashConnectionWire `json:"connections"`
	}
	if err := json.Unmarshal(data, &wire); err != nil {
		return ClashConnections{}, fmt.Errorf("decoding /connections: %w", err)
	}
	connections := make([]ClashConnection, 0, len(wire.Connections))
	for _, entry := range wire.Connections {
		connection := ClashConnection{
			ID: entry.ID, Chains: nonNilSlice(entry.Chains),
			Upload: uint64(max(entry.Upload, 0)), Download: uint64(max(entry.Download, 0)),
		}
		if entry.Metadata != nil {
			connection.Network = entry.Metadata.Network
			connection.Host = entry.Metadata.Host
			connection.DestinationIP = entry.Metadata.DestinationIP
			connection.ProcessPath = entry.Metadata.ProcessPath
		}
		connections = append(connections, connection)
	}
	return ClashConnections{Connections: connections}, nil
}
